variable "vpc_name" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "subnet_az" {}
variable "aws_region" {}
variable "ingress_value" {}
variable "ami_id" {}
variable "key_name" {}